{"end_datetime": "2021-02-09T15:32:08.475807", "exit_code": 0, "hostname": "inspection-tf-dm-tf24-23d24403-1441347026", "hwinfo": {"cpu_features": {"flags": ["3dnowprefetch", "abm", "adx", "aes", "apic", "arat", "arch_capabilities", "avx", "avx2", "avx512bw", "avx512cd", "avx512dq", "avx512f", "avx512vl", "bmi1", "bmi2", "clflush", "clflushopt", "clwb", "cmov", "constant_tsc", "cpuid", "cpuid_fault", "cx16", "cx8", "de", "ept", "erms", "f16c", "flexpriority", "fma", "fpu", "fsgsbase", "fxsr", "hle", "hypervisor", "ibpb", "ibrs", "invpcid", "invpcid_single", "lahf_lm", "lm", "mca", "mce", "md_clear", "mmx", "movbe", "mpx", "msr", "mtrr", "nopl", "nx", "ospke", "osxsave", "pae", "pat", "pcid", "pclmulqdq", "pdpe1gb", "pge", "pku", "pni", "popcnt", "pse", "pse36", "pti", "rdrand", "rdrnd", "rdseed", "rdtscp", "rep_good", "rtm", "sep", "smap", "smep", "ss", "ssbd", "sse", "sse2", "sse4_1", "sse4_2", "ssse3", "stibp", "syscall", "tpr_shadow", "tsc", "tsc_adjust", "tsc_deadline_timer", "tsc_known_freq", "tscdeadline", "umip", "vme", "vmx", "vnmi", "vpid", "x2apic", "xgetbv1", "xsave", "xsavec", "xsaveopt", "xsaves", "xtopology"], "hz_actual": [2095076000, 0], "hz_actual_raw": null, "hz_advertised": [2095076000, 0], "hz_advertised_raw": null, "l1_data_cache_size": 32768, "l1_instruction_cache_size": 32768, "l2_cache_size": 4194304, "l3_cache_size": 16777216}, "cpu_info": {"arch": "X86_64", "arch_string_raw": "x86_64", "bits": 64, "brand_raw": "Intel Xeon Processor (Skylake, IBRS)", "count": 64, "cpuinfo_version": [7, 0, 0], "cpuinfo_version_string": "7.0.0", "family": 6, "hz_actual_friendly": "2.0951 GHz", "hz_advertised_friendly": "2.0951 GHz", "l2_cache_associativity": 8, "l2_cache_line_size": 512, "model": 85, "stepping": 4, "vendor_id_raw": "GenuineIntel"}, "cpu_type": {"has_3dnow": false, "has_3dnowext": false, "has_Altivec": null, "has_f00f_bug": null, "has_fdiv_bug": null, "has_mmx": true, "has_sse": true, "has_sse2": true, "has_sse3": true, "has_ssse3": true, "is_32bit": false, "is_64bit": true, "is_AMD": false, "is_AMD64": false, "is_Alpha": null, "is_Athlon64": false, "is_AthlonHX": false, "is_AthlonK6": false, "is_AthlonK6_2": false, "is_AthlonK6_3": false, "is_AthlonK7": false, "is_AthlonMP": false, "is_Celeron": false, "is_Core2": false, "is_EV4": null, "is_EV5": null, "is_EV56": null, "is_Hammer": false, "is_Intel": true, "is_Itanium": null, "is_Nocona": false, "is_Opteron": false, "is_PCA56": null, "is_Pentium": false, "is_PentiumII": false, "is_PentiumIII": false, "is_PentiumIV": false, "is_PentiumM": false, "is_PentiumMMX": false, "is_PentiumPro": false, "is_Power": null, "is_Power7": null, "is_Power8": null, "is_Power9": null, "is_Prescott": false, "is_XEON": true, "is_Xeon": true, "is_i386": null, "is_i486": null, "is_i586": false, "is_i686": true, "is_singleCPU": false, "nbits": "64", "ncpus": 64, "not_impl": null, "try_call": null}, "platform": {"architecture": ["64bit", ""], "machine": "x86_64", "node": "inspection-tf-dm-tf24-23d24403-1441347026", "platform": "Linux-4.18.0-193.41.1.el8_2.x86_64-x86_64-with-redhat-8.2-Ootpa", "processor": "x86_64", "release": "4.18.0-193.41.1.el8_2.x86_64", "version": "#1 SMP Wed Jan 13 11:33:33 EST 2021"}}, "os_release": {"ansi_color": "0;31", "bug_report_url": "https://bugzilla.redhat.com/", "cpe_name": "cpe:/o:redhat:enterprise_linux:8.3:GA", "home_url": "https://www.redhat.com/", "id": "rhel", "id_like": "fedora", "name": "Red Hat Enterprise Linux", "platform_id": "platform:el8", "pretty_name": "Red Hat Enterprise Linux 8.3 (Ootpa)", "redhat_bugzilla_product": "Red Hat Enterprise Linux 8", "redhat_bugzilla_product_version": "8.3", "redhat_support_product": "Red Hat Enterprise Linux", "redhat_support_product_version": "8.3", "version": "8.3 (Ootpa)", "version_id": "8.3"}, "runtime_environment": {"cuda_version": null, "hardware": {"cpu_family": 6, "cpu_model": 85}, "operating_system": {"name": "rhel", "version": "8.3"}, "python_version": "3.8"}, "script_sha256": "1ce2ae4cf0da06c8c55b99be8beb31cae7c6801bb99664451b06d064912e5d8b", "start_datetime": "2021-02-09T15:31:44.561678", "stderr": "2021-02-09 15:31:45.285696: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n2021-02-09 15:31:45.285770: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\nDTYPE set to float32\nDEVICE set to cpu\nREPS set to 50\nMINI_BATCH set to 40\nMATRIX size set to 512\n# Version: 2.4.0, path: ['/home/amun/venv/lib64/python3.8/site-packages/tensorflow', '/home/amun/venv/lib64/python3.8/site-packages/tensorflow_estimator/python/estimator/api/_v2', '/home/amun/venv/lib64/python3.8/site-packages/tensorboard/summary/_tf', '/home/amun/venv/lib64/python3.8/site-packages/tensorflow', '/home/amun/venv/lib64/python3.8/site-packages/tensorflow/_api/v2']\n2021-02-09 15:31:46.542814: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set\n2021-02-09 15:31:46.543073: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n2021-02-09 15:31:46.543115: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n2021-02-09 15:31:46.543155: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (inspection-tf-dm-tf24-23d24403-1441347026): /proc/driver/nvidia/version does not exist\n2021-02-09 15:31:46.543584: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512F\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2021-02-09 15:31:46.554392: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\n512 x 512 matmul took:   \t402.4494 ms,\t 13.65 GFLOPS\nFailed to obtain AICoE specific build information for TensorFlow\nTraceback (most recent call last):\n  File \"/home/amun/script\", line 70, in _get_aicoe_tensorflow_build_info\n    with open(build_info_path, 'r') as build_info_file:\nFileNotFoundError: [Errno 2] No such file or directory: '/home/amun/venv/lib64/python3.8/site-packages/tensorflow-2.4.0.dist-info/build_info.json'\n", "stdout": {"@parameters": {"device": "cpu", "dtype": "float32", "matrix_size": 512, "mini_batch": 40, "reps": 50}, "@result": {"elapsed": 402.44942050776444, "rate": 13.647531362003875}, "component": "tensorflow", "name": "PiMatmul", "tensorflow_aicoe_buildinfo": null, "tensorflow_upstream_buildinfo": {"cpu_compiler": "/usr/bin/gcc-5", "cuda_compute_capabilities": ["sm_35", "sm_50", "sm_60", "sm_70", "sm_75", "compute_80"], "cuda_version": "11.0", "cudnn_version": "8", "is_cuda_build": true, "is_rocm_build": false}}, "usage": {"ru_idrss": 0, "ru_inblock": 0, "ru_isrss": 0, "ru_ixrss": 0, "ru_majflt": 0, "ru_maxrss": 302816, "ru_minflt": 52307, "ru_msgrcv": 0, "ru_msgsnd": 0, "ru_nivcsw": 66502, "ru_nsignals": 0, "ru_nswap": 0, "ru_nvcsw": 220836, "ru_oublock": 32, "ru_stime": 4.537801, "ru_utime": 19.103392}, "inspection_document_id": "inspection-tf-dm-tf24-23d24403"}
